Update test-coverage.yaml

diff --git a/.github/workflows/pkgdown.yaml b/.github/workflows/pkgdown.yaml
--- a/.github/workflows/pkgdown.yaml
+++ b/.github/workflows/pkgdown.yaml
@@ -1,41 +1,61 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
     branches: [main]
-  release:
-    types: [published]
-  workflow_dispatch:
+  pull_request:
 
-name: pkgdown
+name: test-coverage.yaml
+
+permissions: read-all
 
 jobs:
-  pkgdown:
+  test-coverage:
     runs-on: ubuntu-latest
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-    permissions:
-      contents: write
-      pages: write
+
     steps:
-      - uses: actions/checkout@v4
-      - uses: r-lib/actions/setup-pandoc@v2
-      - uses: r-lib/actions/setup-r@v2
+      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
+
+      - uses: ./setup-r
         with:
           use-public-rspm: true
-      - uses: r-lib/actions/setup-r-dependencies@v2
+
+      - uses: ./setup-r-dependencies
         with:
-          extra-packages: any::pkgdown, local::.
-      - name: Debug Info
+          extra-packages: any::covr, any::xml2
+          needs: coverage
+
+      - name: Test coverage
         run: |
-          echo "Working directory:"
-          pwd
-          echo "Files in directory:"
-          ls -alh
-      - name: Build site
-        run: Rscript -e 'pkgdown::build_site()'
-      - name: Deploy to GitHub pages 🚀
-        if: github.event_name != 'pull_request'
-        uses: JamesIves/github-pages-deploy-action@v4.5.0
+          cov <- covr::package_coverage(
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
+          )
+          covr::to_cobertura(cov)
+        shell: Rscript {0}
+
+      - uses: codecov/codecov-action@f1b7348826d750ac29741abc9d1623d8da5dcd4f
         with:
-          clean: false
-          branch: gh-pages
-          folder: .
+          # Fail if error if not on PR, or if on PR and token is given
+          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
+          file: ./cobertura.xml
+          plugin: noop
+          disable_search: true
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
